Update role for ansible 2.18.0, galaxy-ng.
Role compliant for galaxy collection deployment.

Breaking:
* 1.0.0 installs required reconfiguration.

Added:
* Molecule unit tests.
* Added bookworm support.
* Preferences.xml per variable setting.
* r_pufky.srv collection integration.
* Support plex version 1.41.4.9399.

Changed:
* Removed lint file overrides.

diff --git a/templates/plexupdate.j2 b/templates/plexupdate.j2
--- a/templates/plexupdate.j2
+++ b/templates/plexupdate.j2
@@ -1,40 +1,51 @@
 #!/bin/bash
 #
-# Update plex server with plexpass token if available.
+# Update Plex server using entitlement token. An entitlement token without
+# PlexPass will just return the latest public release. Must be run as root to
+# install new packages.
+#
+# Exit Codes:
+#   0: success - plex on most current release
+#   1: failure - missing Preferences.xml
+#   2: failure - incomplete download
 #
 # Reference:
-# * https://github.com/linuxserver/docker-plex/blob/master/root/etc/cont-init.d/60-plex-update
+# * https://github.com/linuxserver/docker-plex/blob/master/root/etc/s6-overlay/s6-rc.d/init-plex-update/run
+# * https://github.com/mrworf/plexupdate
+
+PLEX_URL_BASE="https://downloads.plex.tv/plex-media-server-new"
+INSTALLED_VERSION=$(dpkg-query --show --showformat='${Version}' plexmediaserver)
 
 if [ ! -e "{{ _plex_library_dir }}/Preferences.xml" ]; then
   echo 'No preference file located: {{ _plex_library_dir }}/Preferences.xml'
   exit 1
 fi
 
-PLEX_TOKEN=$( sed -n 's/.*PlexOnlineToken="//p' "{{ _plex_library_dir }}/Preferences.xml" | sed "s/\".*//")
-
-# An entitlement token without plexpass will just return the latest public release.
+PLEX_TOKEN=$( sed --silent 's/.*PlexOnlineToken="//p' "{{ _plex_library_dir }}/Preferences.xml" | sed "s/\".*//")
 if [ -z "$PLEX_TOKEN" ]; then
-  echo 'Plex entitlement token not found'
-  exit 2
+  PLEX_TOKEN='no-entitlement-token'  # ensure token defined for check
 fi
 
-INSTALLED_VERSION=$(dpkg-query -W -f='${Version}' plexmediaserver)
-REMOTE_VERSION=$(curl -s "https://plex.tv/downloads/details/5?distro=debian&build=linux-{{ plex_arch_generic }}&channel=8&X-Plex-Token=${PLEX_TOKEN}"| grep -oP 'version="\K[^"]+' | tail -n 1 )
-
+REMOTE_VERSION=$(curl --silent "https://plex.tv/downloads/details/5?distro=debian&build=linux-{{ plex_service_arch_generic }}&channel={{ plex_butler_update_channel }}&X-Plex-Token=${PLEX_TOKEN}"| grep --only-matching --perl-regexp 'version="\K[^"]+' | tail --lines 1 )
 if [[ "$REMOTE_VERSION" == "$INSTALLED_VERSION" ]]; then
   exit 0
 fi
 
+PLEX_PKG="plexmediaserver_${REMOTE_VERSION}_{{ plex_service_arch }}.deb"
+PLEX_URL="${PLEX_URL_BASE}/${REMOTE_VERSION}/debian/${PLEX_PKG}"
+PLEX_DEB="/tmp/${PLEX_PKG}"
+
 rm -f /tmp/plexmediaserver_*.deb
-wget --no-verbose --directory-prefix=/tmp "https://downloads.plex.tv/plex-media-server-new/${REMOTE_VERSION}/debian/plexmediaserver_${REMOTE_VERSION}_{{ plex_arch }}.deb"
+curl --silent --output-dir /tmp -O "${PLEX_URL}"
 last=$?
 
 # Verify non-partial download
-if [[ "$last" -gt "0" ]] || [[ $(stat -c %s /tmp/plexmediaserver_"${REMOTE_VERSION}"_{{ plex_arch }}.deb) -lt 10000 ]]; then
+if [[ "${last}" -gt "0" ]] || [[ $(stat --format %s "${PLEX_DEB}") -lt 10000 ]]; then
   echo 'Package download failed.'
-  exit 3
+  exit 2
 else
-  dpkg -i --force-confold /tmp/plexmediaserver_"${REMOTE_VERSION}"_{{ plex_arch }}.deb
+  dpkg --install --force-confold "${PLEX_DEB}"
   systemctl restart plexmediaserver.service
   rm -f /tmp/plexmediaserver_*.deb
+  exit 0
 fi
